export const FETCH_PATIENTS_REQUEST = "FETCH_PATIENTS_REQUEST";
export const FETCH_PATIENTS_SUCCESS = "FETCH_PATIENTS_SUCCESS";
export const FETCH_PATIENTS_FAILURE = "FETCH_PATIENTS_FAILURE";
export const CREATE_PATIENT_REQUEST = "CREATE_PATIENT_REQUEST";
export const DELETE_PATIENT_REQUEST = "DELETE_PATIENT_REQUEST";
